---
# Rule hierarchy yaml
Production:
  rules:
    - TemplateCheck
  Assets:
    rules:
    Modeling:
      rules:
      Modeling:
        rules:
          - HaveOnlyGeoAtRoot
          - HaveShaderGroupWellNamed
          - SMIsWellSetForModeling
          - AllGeoShouldHaveATRSof0
          - ThereShouldBeLessThanXObject
          - ThereShouldBeLessThanXMaterial
    Shading:
      rules:
      Lookdev:
        rules:
          # - HaveMaterialPreviewCheck

  Shots:
    rules:
    Lighting:
      rules:
      Lighting SEQ:
        rules:
