---
# Rule hierarchy yaml
IsEnable: on
Production:
  rules:
    # - TemplateCheck|ERROR|WARNING
  Assets:
    rules:
    Modeling:
      rules:
      Modeling:
        rules:
          # - HaveOnlyGeoAtRoot|WARNING
          - NamingHierarchyModeling|WARNING
          - NamingShadingGroup|WARNING
          # - SMIsWellSetForModeling|WARNING
          - AllGeoShouldHaveATRSof0|WARNING
          - ThereShouldBeLessThanXObject|WARNING
          - ThereShouldBeLessThanXMaterial|WARNING
    Shading:
      rules:
      Lookdev:
        rules:
          # - HaveMaterialPreviewCheck
  Shots:
    rules:
    Lighting:
      rules:
      Lighting SEQ:
        rules:
    Anim:
      rules:
      Anim:
        rules:
          - NamingHierarchyAnimation
          - NamingCamera
    Layout:
      rules:
      Layout:
        rules:
          # - NamingHierarchyLayout
          - NamingCamera